run:
  deadline: 5m

output:
  sort-results: true

linters:
  enable:
    - gofumpt
    - goimports
    - revive
    - misspell
    - promlinter
    - tenv
    - errorlint
    - errname
    - exportloopref
    - predeclared
    - contextcheck
    - exhaustive
    - gocritic
    - importas
    - nakedret
    - prealloc
    - unconvert
    - testifylint
    - godot

issues:
  max-same-issues: 0

linters-settings:
  goimports:
    local-prefixes: github.com/cloudflare/pint
  gofumpt:
    extra-rules: true
  nakedret:
    max-func-lines: 0
