name: Test Go code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: |
          mkdir -p .cover
          echo 'mode: atomic' > .cover/coverage.out
          go test \
                -covermode=atomic \
                -coverprofile=.cover/coverage.out \
                -coverpkg=./... \
                -race \
                -count=5 \
                -timeout=10m \
                ./...

      - name: Check for local changes
        run: git diff --exit-code

      - name: Report code coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./.cover/coverage.out
