name: Test Go code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: make test

      - name: Check for local changes
        run: git diff --exit-code

      - name: Report code coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./.cover/coverage.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
